### ISSUE TITLE
RPC server only responds with empty message

### ISSUE THREAD

**Issue by smogm** [dzimbeck/BitBay#17]
I tried both bitbay-qt and bitbayd (newest github clone), and everytime I send a request I only get "empty replys".

This is what I send:
``
curl -u bitbayrpc:BBZP3Q4MqWqksU -X POST -d '{"id": "0", "method":"getinfo",  "params": []}' -H 'content-type: application/json' http://127.0.0.1:25001
``
Curl always reports:
``
curl: (52) Empty reply from server
``
I tried GET and POST as well as digest auth. Everytime I got the same behaviour.

The same Curl command (as well as the bitcoin core `getinfo` RPC call) works for many other currency wallets, only bitbay wallet is making troubles.
 
The port, user and password are configured in bitbay.conf and netstat is showing bitbayd/bitbay-qt process listening on this port, so to that point everthing seems to be correct.
Looks like either a problem in my command or a problem in bitbay wallet RPC implementation?

In case of invalid/malformed JSON command, other wallets of other currencies also respond an adequate JSON encoded error message in the case the given command is invalid. Bitbay just seem to do nothing?

**Comment by yshurik** [comment]
Please provide additional info:
* Platform (mac,win,linux)
* Qt wallet / bitbayd versions
* Command-line options you used to start bitbayd/walet (wallet has xml-rpc off until -server specified)
* Copy of your bitbay.conf and specify location of it

**Comment by smogm** [comment]
- Platform: Linux
- Version: `BitBay version v2.0.0.0-g32a928e`
- CLI Options: `./bitbayd -server`
- bitbay.conf:
```
rpcuser=bitbayrpc
rpcpassword=BBZP3Q4MqWqksU2J6SDXBME9qakXoGG1dRTCzL2YtdyS
```

I started bitbayd with strace to verify that it is opening the correct bitbay.conf reading its correct content:
```
[...]  
openat(AT_FDCWD, "/home/smogm/.bitbay/bitbay.conf", O_RDONLY) = 3
read(3, "rpcuser=bitbayrpc\nrpcpassword=BB"..., 8191) = 75
read(3, "", 8191)                       = 0
close(3)                                = 0
[...]
```
Which seems correct.

Netstat output:
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
[...]
tcp        0      0 0.0.0.0:19914           0.0.0.0:*               LISTEN      1000       3941744    1972/./bitbayd
[...]
```
So the daemon is listening.

Curl verbose:
```
curl -v -u bitbayrpc:BBZP3Q4MqWqksU2J6SDXBME9qakXoGG1dRTCzL2YtdyS -X POST -d '{"id": "0", "method":"getinfo",  "params": []}' -H 'content-type: application/json' http://127.0.0.1:19914
Note: Unnecessary use of -X or --request, POST is already inferred.
* Rebuilt URL to: http://127.0.0.1:19914/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 19914 (#0)
* Server auth using Basic with user 'bitbayrpc'
> POST / HTTP/1.1
> Host: 127.0.0.1:19914
> Authorization: Basic Yml0YmF5cnBjOkJCWlAzUTRNcVdxa3NVMko2U0RYQk1FOXFha1hvR0cxZFJUQ3pMMll0ZHlT
> User-Agent: curl/7.52.1
> Accept: */*
> content-type: application/json
> Content-Length: 46
>
* upload completely sent off: 46 out of 46 bytes
* Curl_http_done: called premature == 0
* Empty reply from server
* Connection #0 to host 127.0.0.1 left intact
curl: (52) Empty reply from server
```
So curl is able to establish a connection and to send the data body.
But then bitbay is simply replying an empty message.

**Comment by yshurik** [comment]
Now I see your confusion.
The port 19914 is "protocol" port for nodes to connect each other.
The rpc port is 19915. 
Qt wallet has the rpc port "off" until "-server" command line option is specified. 
bitbayd has it open by default but only on 127.0.0.1 (localhost) - you can change via command line.

**Comment by smogm** [comment]
According to the help and code the default RPC port is 19914 too, not 19915:
```
 -rpcport=<port>        Listen for JSON-RPC connections on <port> (default: 19914 or testnet: 21914)
```
Maybe this should be fixed anyway.
But port 19915 is not opened by bitbayd by default.

So what now I got it working with
```
./bitbayd -server -rpcport=19915
```
Somewhat tricky and misleading from the help ;)

Thank you for your help!

**Comment by yshurik** [comment]
You are right. The "--help" should be adjusted.

**Comment by dzimbeck** [comment]
Thanks for reporting the typo, we will update this shortly.
