### ISSUE TITLE
line 1: ./Halo: No such file or directory

### ISSUE THREAD

**Issue by gjhklfdsa** [dzimbeck/BitBay#30]
**Description**: I get this error when trying to run on Linux:

```
usr@USR:~$ Applications/BitBay/BitBay.sh
Applications/BitBay/BitBay.sh: line 1: ./Halo: No such file or directory
usr@USR:~$ 
```

**OS**: Debian Stable

**Comment by dzimbeck** [comment]
Halo should be in the directory check to see if you are running 32 or 64 bit package. You can just run it manually if you want. Also best to report on the forums of bitbay.market since this github is for QT source code (not the Halo package)
