### ISSUE TITLE
stdout pollution on bitbayd execution

### ISSUE THREAD

**Issue by g1itch** [dzimbeck/BitBay#5]
Every time I run bitbayd it prints to stdout this messages:
```
block.GetHash() == 0000075685d3be1f253ce777174b1594354e79954d2a32a6f77fe9cba00e6467
block.GetHash() == 0000075685d3be1f253ce777174b1594354e79954d2a32a6f77fe9cba00e6467
block.GetHash() == 0000075685d3be1f253ce777174b1594354e79954d2a32a6f77fe9cba00e6467
```

Unfortunately I can't find the source.

**Comment by dzimbeck** [comment]
This is the genesis block hash, perhaps the bitbayd you have is an older version? I don't see any printf statements for this. So perhaps rebuild it and if you see this again we can open the issue and see where that gets printed from.
