### ISSUE TITLE
Upgrade LevelDB to 1.9 or grater

### ISSUE THREAD

**Issue by smogm** [dzimbeck/BitBay#9]
Please update the leveldb dep to version 1.9 or later.
This version is ready for ARM64 compilation.

Thank you!

**Comment by yshurik** [comment]
Upgrade of leveldb to 1.20 is done in "main" bitbay repo (https://github.com/bitbaymarket/bitbay-core)

**Comment by dzimbeck** [comment]
This is still the main repo for auditing purposes and exchanges however yshurik has been doing a lot contributing to the code base. Will most likely merge that commit.
